### ISSUE TITLE
"expected package `QOI [4b34888f]` to be registered" error

### ISSUE THREAD

**Issue by thompsonmj** [KristofferC/QOI.jl#10]
I am trying to use Pluto on Binder to load Manifest and Project files from an online repository. 

When I download, activate, and instantiate these files, I get the error in the title.

See this [Discourse post](https://discourse.julialang.org/t/pluto-on-binder-use-a-repo-environment-rather-than-pluto-managed-environment/75311/4?u=thompsonmj) for more details.

Not sure if this is an issue with QOi itself, [Pluto on Binder](https://github.com/fonsp/pluto-on-binder/issues/18), or something else?

**Comment by KristofferC** [comment]
I don't think this is an issue with the package. I have no problem addingg it and it is used in CI systems for other packages.

**Comment by thompsonmj** [comment]
OK, thanks for looking into. Would you suspect `Pkg` to be the issue? Trying to figure out where to dig ...

**Comment by KristofferC** [comment]
To me it seems like a problem of an out of date registry.
